name: Code Quality and Security Check

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  code-quality-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies for quality checks
        run: |
          python -m pip install --upgrade pip flake8 mypy

      - name: Run Mypy
        run: mypy . --ignore-missing-imports

      - name: Run Flake8
        run: flake8 .

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true # This allows the workflow to continue even if vulnerabilities are found, for reporting purposes

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
        if: always() # This step will run even if the previous step fails
