name: Code Quality and Type Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  code-quality-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy
      
      - name: Run Flake8
        run: flake8 .
      
      - name: Run mypy
        run: mypy .